# -*- coding: utf-8 -*-
"""Copy of HR_Analytics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bPCDV2pweADJJxnOz5inzam8UGDwJ95U
"""

import pandas as pd

data = pd.read_csv("Uncleaned_employees_final_dataset.csv")

data.head()

data.shape

"""### STEP-1 Removing duplicate rows"""

data.duplicated().sum()

data.drop_duplicates(inplace=True)

data.shape

"""### STEP-2 Irrelevant data type values"""

data.columns

data["department"].value_counts()

data["region"].value_counts()

data["education"].value_counts()

data["gender"].value_counts()

data.recruitment_channel.value_counts()

data.no_of_trainings.value_counts()

data.age.value_counts()

data.previous_year_rating.value_counts()

data.length_of_service.value_counts()

data.KPIs_met_more_than_80.value_counts()

data.awards_won.value_counts()

data.avg_training_score.value_counts()

"""### STEP-3 Removing NaN Values"""

data.isna().sum()

data.dropna(inplace=True)

data.shape

data.loc[data.avg_training_score >= 99]

data.to_csv("cleaned.csv",encoding="utf-8",index=False)